name: MacOS

on: [push]

jobs:
  verify-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master

    - name: Configure
      run: 	cmake -B build -G "Ninja Multi-Config" -S example

    - name: Build
      run: cmake --build build --config Release
