option(GLFW_BUILD_DOCS OFF)
option(GLFW_BUILD_EXAMPLES OFF)
option(GLFW_BUILD_TESTS OFF)
option(GLFW_INSTALL OFF)
add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/glfw)

if(USE_SHARED_LIBS)
	set_target_properties(glfw PROPERTIES FOLDER 3rdparty/Shared/glfw)
	set_target_properties(update_mappings PROPERTIES FOLDER 3rdparty/Shared/glfw)
else()
	set_target_properties(glfw PROPERTIES FOLDER 3rdparty/Static/glfw)
	set_target_properties(update_mappings PROPERTIES FOLDER 3rdparty/Static/glfw)
endif()

set_target_properties(glfw PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${FINAL_BIN_DIR}")
set_target_properties(glfw PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${FINAL_BIN_DIR}")
set_target_properties(glfw PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${FINAL_BIN_DIR}")

set(GLFW_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/3rdparty/glfw/include)
set(GLFW_DEFINITIONS -DGLFW_INCLUDE_NONE)
set(GLFW_LIBRARIES ${GLFW_LIBRARIES} glfw)
